export const LOG_OUT = "LOG_OUT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const STORE_USER_ERROR_MSG = "STORE_USER_ERROR_MSG";
export const CHECKOUT = "CHECKOUT";
export const LOAD_COURSE_DETAIL = "LOAD_COURSE_DETAIL";

export const UPDATE_CART = "UPDATE_CART";
export const CLEAR_CART = "CLEAR_CART";

export const CART_FETCHED = "CART_FETCHED";
export const ITEM_REMOVED_FROM_CART = "ITEM_REMOVED_FROM_CART";
export const ORDER_REQUEST = "ORDER_REQUEST";
export const ORDER_PREVIEW_SUCCESS = "ORDER_PREVIEW_SUCCESS";
export const ORDER_PREVIEW_ERROR = "ORDER_PREVIEW_ERROR";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const SET_ORDER_PREVIEW = "SET_ORDER_PREVIEW";
export const ORDERS_FETCH_START = "ORDERS_FETCH_START";
export const ORDERS_FETCHED = "ORDERS_FETCHED";
export const NO_ORDER_FETCHED = "NO_ORDER_FETCHED";
export const ORDERS_FETCH_ERROR = "ORDERS_FETCH_ERROR";
export const TOOGLE_ORDER_SEARCH = "TOOGLE_ORDER_SEARCH";
export const ORDER_REFRESH_START = "ORDER_REFRESH_START";
export const UPDATE_QTY = "UPDATE_QTY";
export const LOAD_BOOK_DETAIL = 'LOAD_BOOK_DETAIL';
export const LOAD_EVENT_DETAIL = 'LOAD_EVENT_DETAIL';


